version: '3'
services:
  cassandraql:
    image: "cassandra:4.0.1"
    container_name: cassandraql
    ports:
        - "9042:9042"
    environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
    volumes:
        - ./cassandra-data:/var/lib/cassandra
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 10s
      timeout: 5s
      retries: 50
  app:
    container_name: devicemanagement
    image: devicemanagement
    build:
      context: app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    restart: on-failure